name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Standard build on Java ${{ matrix.java }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: ['8', '11']
        experimental: [false]
        include:
          - java: '16'
            experimental: true
          - java: '17'
            experimental: true
    continue-on-error: ${{ matrix.experimental }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Configure Java
      uses: actions/setup-java@v3
      with:
        java-version: '${{ matrix.java }}'
        cache: 'maven'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn -B --no-transfer-progress package --file pom.xml